### ISSUE TITLE
Bonus Features

### ISSUE THREAD

**Issue by ssoonmi** [johnnyhperkins/StayWithMe#1]
Could you come up with some bonus features and put them on your MVP List? I think that you can definitely finish your MVP's within the two weeks given. With your knowledge, I expect that the MVP features will be fully complete within the two weeks, so I think you should flush out bonus features to work on after you complete the MVP's.

**Comment by johnnyhperkins** [comment]
Added some bonus stuff! As I go hopefully I'll come up with additional features and add them to the list.
