### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by ssoonmi** [johnnyhperkins/StayWithMe#2]
`users`

- [x] should have a unique `email`
----------------------------------------

`listings`
- [x] instead of `location`, may want integers of `longitude` and `latitude` and an index on them to allow for better searching by location
----------------------------------------

`reviews`
- [x] a `user` should only be able to `review` once
- [x] should have a separate index on `listing_id` and `user_id`, not just `[listing_id, user_id]`
----------------------------------------

`listing_availabilities`
- [x] should have a separate index on `listing_id`, `start_date` and `end_date`, not just `[listing_id, start_date, end_date]`
----------------------------------------

`bookings`
- [x] should have a separate index at least on `listing_id` and `user_id`, not just `[listing_id, user_id, start_date, end_date]`
- [x] should have a table column specifying if a `booking` is `approved`, `denied`, or `pending` (or maybe even `canceled`)
----------------------------------------

Awesome job!
If you don't think some of these suggestions are appropriate, please comment below!

**Comment by ssoonmi** [comment]
You can have an index on both `user_id` and `listing_id` and constrain it with uniqueness.

**Comment by johnnyhperkins** [comment]
Ah ok, cool. Added that constraint to the schema

**Comment by ssoonmi** [comment]
Great job!
