### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by ssoonmi** [johnnyhperkins/StayWithMe#4]
## Backend Routes
- [x] change routes so foreign keys go in between foreign table and primary table. (e.g. `/api/listings/:listing_id/bookings`) (for some routes in `listings`, `reviews`, and `listing_availabilities`)
---
`reviews`
- [x] may want to add a feature to edit `reviews`
`bookings`
---
`bookings`
- [x] you may want to have separate routes to update the `status` of a `booking` (e.g `/api/bookings/:id/approve`, etc.)
---
## Frontend Routes
- [x] add a route to edit/create a `listing`
- [x] may want to have a route to edit a `booking`
- Awesome job with the frontend routes!

**Comment by johnnyhperkins** [comment]
Great catches... Not sure how I overlooked those routes! Thanks
