### ISSUE TITLE
User Auth Review I

### ISSUE THREAD

**Issue by ssoonmi** [johnnyhperkins/StayWithMe#5]
- [x] Demo log in doesn't work
- [x] Sign up doesn't work
- [x] Log in doesn't work
- [x] nav bar looks different on the splash page when a user isn't signed in
- [x] implement a splash page when a user isn't logged in
- [x] don't let modal flash when switching login and signup
- [x] placeholders on the `email` and `password` inputs are a little bolder than Airbnb's
- [x] font-weights on the submit buttons look a little too bold
- [x] Awesome job with the styling of the nav bar!
- [x] the nav bar links seem to be slightly smaller than Airbnb's

#### Log in Form
- [x] `Log in to continue` on Airbnb website looks different from your `Log In with Facebook or Google`
- [x] continuing with `Facebook` or `Google` is shown on the bottom of the form

**Comment by johnnyhperkins** [comment]
Hadn't run db:migrate on heroku... oops. User creation log in and demo should all work now. Will start on other items now... let me know if this git flow seems right: I'm currently on a new branch called listings. So I'll commit changes to that, switch to master, create a new branch from master make changes to that and then remerge to master when done..?

**Comment by ssoonmi** [comment]
You should be making changes on the auth branch since youre changing the auth feature. Then rebase your listings branch to the auth branch

**Comment by johnnyhperkins** [comment]
Mmkay cool, had some diffs between master and userauth but was able to rebase master to userauth without conflicts so, good to go! Thanks
